// client/components/CommandSidebar.tsx
//
// "Commands" panel of the conversation sidebar: a flat, filterable audit
// trail of every command the agent ran (plus file edits / other tool calls),
// derived client-side from the already-loaded transcript events. Entries jump
// to their transcript row on click; the shell-command subset can be exported
// as a replayable .sh script.
import { useMemo, useState } from "react";
import type { CommandCategory, CommandEntry } from "../lib/events.js";
import { formatClockTime } from "../lib/time.js";

type Filter = "all" | CommandCategory;

const FILTERS: { key: Filter; label: string }[] = [
  { key: "all", label: "All" },
  { key: "command", label: "Commands" },
  { key: "edit", label: "Edits" },
  { key: "other", label: "Other" },
];

const STATUS_GLYPH: Record<CommandEntry["status"], { glyph: string; cls: string; title: string }> = {
  ok: { glyph: "\u2714", cls: "text-[var(--color-text-success,#22c55e)]", title: "Succeeded" },
  error: { glyph: "\u2718", cls: "text-[var(--color-text-critical)]", title: "Failed" },
  pending: { glyph: "\u27F3", cls: "text-blue-400 animate-pulse", title: "Running / awaiting result" },
};

function downloadScript(entries: CommandEntry[], conversationId: string) {
  const commands = entries.filter((e) => e.category === "command");
  const body = [
    "#!/usr/bin/env bash",
    `# Agent commands from OpenHands conversation ${conversationId}`,
    `# Exported ${new Date().toISOString()}`,
    "#",
    "# SAFETY: these commands were generated by an AI agent and are exported",
    "# verbatim. Review every line, then delete the guard below to enable.",
    'echo "Refusing to run: review this script, then remove the guard line." >&2; exit 1',
    "",
    ...commands.map((e) => `# ${e.timestamp}${e.status === "error" ? " (failed)" : ""}\n${e.text}\n`),
  ].join("\n");
  const url = URL.createObjectURL(new Blob([body], { type: "text/x-shellscript" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `openhands-${conversationId.slice(0, 8)}-commands.sh`;
  a.click();
  URL.revokeObjectURL(url);
}

function CopyButton({ text, title }: { text: string; title: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={(ev) => {
        ev.stopPropagation();
        void navigator.clipboard?.writeText(text).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 1_200);
        });
      }}
      className="shrink-0 rounded px-1 text-[10px] text-[var(--color-text-muted)] opacity-0 transition-opacity hover:text-[var(--color-text-default)] group-hover:opacity-100"
      title={title}
      data-testid="openhands-command-copy"
    >
      {copied ? "\u2713" : "\u29C9"}
    </button>
  );
}

function EntryRow({ entry, onJump }: { entry: CommandEntry; onJump: (id: string) => void }) {
  const status = STATUS_GLYPH[entry.status];
  return (
    <li className="group" data-status={entry.status} data-category={entry.category}>
      <button
        onClick={() => onJump(entry.id)}
        className="flex w-full flex-col gap-0.5 rounded px-2 py-1.5 text-left hover:bg-[var(--color-background-muted,rgba(127,127,127,0.10))]"
        title="Jump to transcript"
        data-testid="openhands-command-entry"
      >
        <span className="flex items-center gap-1.5 text-[10px] text-[var(--color-text-muted)]">
          <span className={`shrink-0 ${status.cls}`} title={status.title} aria-hidden>{status.glyph}</span>
          <span className="shrink-0 font-medium">{entry.label}</span>
          {entry.timestamp && (
            <time dateTime={entry.timestamp} className="ml-auto shrink-0 tabular-nums opacity-70">
              {formatClockTime(entry.timestamp)}
            </time>
          )}
          <CopyButton text={entry.text} title="Copy command" />
        </span>
        <span className="truncate font-mono text-[11px]">
          {entry.category === "command" && <span className="text-[var(--color-text-muted)]">$ </span>}
          {entry.text}
        </span>
        {entry.outputPreview && (
          <span className="truncate font-mono text-[10px] text-[var(--color-text-muted)] opacity-80">
            └ {entry.outputPreview}
          </span>
        )}
      </button>
    </li>
  );
}

export function CommandsPanel({
  entries,
  conversationId,
  onJump,
}: {
  entries: CommandEntry[];
  conversationId: string;
  onJump: (eventId: string) => void;
}) {
  const [filter, setFilter] = useState<Filter>("all");
  const [query, setQuery] = useState("");

  const visible = useMemo(() => {
    const q = query.trim().toLowerCase();
    return entries.filter(
      (e) =>
        (filter === "all" || e.category === filter) &&
        (!q || e.text.toLowerCase().includes(q) || e.label.toLowerCase().includes(q)),
    );
  }, [entries, filter, query]);

  const commandCount = useMemo(() => entries.filter((e) => e.category === "command").length, [entries]);
  const allCommandsText = useMemo(
    () => entries.filter((e) => e.category === "command").map((e) => e.text).join("\n"),
    [entries],
  );

  return (
    <div
      className="flex min-h-0 flex-1 flex-col"
      aria-label="Agent commands"
      data-testid="openhands-commands-panel"
    >
      <div className="flex items-center gap-1.5 border-b border-[var(--color-border-default)] px-3 py-2">
        <span
          className="shrink-0 text-[11px] font-medium uppercase tracking-wide text-[var(--color-text-muted)]"
          title="Agent commands"
          data-testid="openhands-command-count"
        >
          {visible.length}{visible.length !== entries.length ? `/${entries.length}` : ""}
        </span>
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value as Filter)}
          className="rounded border border-[var(--color-border-default)] bg-transparent px-1.5 py-0.5 text-[11px] text-[var(--color-text-muted)] pointer-coarse:py-2 pointer-coarse:text-base"
          aria-label="Filter commands"
          data-testid="openhands-command-filter"
        >
          {FILTERS.map((f) => (
            <option key={f.key} value={f.key}>{f.label}</option>
          ))}
        </select>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search…"
          className="min-w-0 flex-1 rounded border border-[var(--color-border-default)] bg-transparent px-2 py-0.5 text-[11px] focus:outline-none pointer-coarse:py-2 pointer-coarse:text-base"
          aria-label="Search commands"
          data-testid="openhands-command-search"
        />
      </div>

      <div className="thin-scrollbar min-h-0 flex-1 overflow-y-auto px-1 py-1">
        {visible.length === 0 ? (
          <div className="px-3 py-8 text-center text-xs text-[var(--color-text-muted)]" data-testid="openhands-command-empty">
            {entries.length === 0 ? "No commands yet." : "No commands match."}
          </div>
        ) : (
          <ul className="space-y-0.5">
            {visible.map((e) => (
              <EntryRow key={e.id} entry={e} onJump={onJump} />
            ))}
          </ul>
        )}
      </div>

      <div className="flex items-center gap-2 border-t border-[var(--color-border-default)] px-3 py-2">
        <button
          onClick={() => void navigator.clipboard?.writeText(allCommandsText)}
          disabled={commandCount === 0}
          className="rounded border border-[var(--color-border-default)] px-2 py-0.5 text-[11px] text-[var(--color-text-muted)] hover:text-[var(--color-text-default)] disabled:opacity-40"
          title="Copy all shell commands to the clipboard"
          data-testid="openhands-command-copy-all"
        >
          Copy all
        </button>
        <button
          onClick={() => downloadScript(entries, conversationId)}
          disabled={commandCount === 0}
          className="rounded border border-[var(--color-border-default)] px-2 py-0.5 text-[11px] text-[var(--color-text-muted)] hover:text-[var(--color-text-default)] disabled:opacity-40"
          title="Download shell commands as a replayable script"
          data-testid="openhands-command-export"
        >
          Export .sh
        </button>
      </div>
    </div>
  );
}
